name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: yourdockerhubusername/sample-webapp
  DEPLOY_ENV: production

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run linter
        run: flake8 .

      - name: Run unit tests
        run: pytest

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to ${{ env.DEPLOY_ENV }}
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-app-url.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy app (example using SSH)
        run: |
          ssh user@your-server "
            docker pull $IMAGE_NAME:latest &&
            docker stop webapp || true &&
            docker rm webapp || true &&
            docker run -d --name webapp -p 80:80 $IMAGE_NAME:latest
          "
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        continue-on-error: true

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Deployment failed. Rolling back..."
          ssh user@your-server "
            docker stop webapp || true &&
            docker rm webapp || true &&
            docker run -d --name webapp -p 80:80 $IMAGE_NAME:previous
          "
